name: Event

on:
  schedule:
    - cron: '40 11 */2 * *'

jobs:
  send_ref_email:
    runs-on: ubuntu-latest
    steps:
      - name: event
        env:
          API_URL: https://bend.vhennus.com/cron_jobs/event
        run: |
          echo "📅 $(date -u): calling $API_URL"
          curl -X GET "$API_URL" \
            -H "Content-Type: application/json" \
            --fail --show-error
